### ISSUE TITLE
Framestepping only works on 24 FPS videos

### ISSUE THREAD

**Issue by Igetin** [ftLoic/Sakuga-Extended#1]
Hi, I checked the code quickly and it seems like the frame control feature has been hardcoded to work only with 24 FPS videos. While most uploads on the booru should have a framerate of 24 FPS, this is not always the case. For example, if the video has a framerate of 30 FPS, some frames are skipped because the current implementation works in the units of 1/24th of a second.

**Comment by NikuKikai** [comment]
(Copy from twitter)
I think length of "frame" should be decided by the framerate(?) that's been created with, that's what animators saw. 
That's to say, even if the video is in 30fps, if the animation is created in 24fps, we should control the video in 24fps. Otherwise, e.g. a cut of 3コマ打ち(each keyframe lasts 3/24frames) will become like 4, 4, 3, 4, 4, 3, 4, 4...

I don't know if there is any animation originally created in a different fps?

**Comment by Igetin** [comment]
Yes, key animators time their cuts with the basis that one second consists of 24 frames, and the [time sheets](https://www.sakugabooru.com/post/show/30383) are also designed for that framerate. However, this does not mean that the _drawings_ will also appear at a constant rate. If you check out the timesheet in the link, you can see that the timing fluctuates between 1s, 2s and 3s within a single second.

(In case you’re not familiar, “1s”, “2s”, “3s”, etc. are English terminology for timing in traditional animation, so “1s” would mean that the drawing changes every subsequent frame (1/24), “2s” for every second frame (2/24), and so on.)

[Here’s](https://www.sakugabooru.com/post/show/25475) an example of a 30 FPS video on the booru.

The framerate may be constant, but the drawing rate isn’t. The current implementation simply rewinds/forwards the time for a 1/24th of a second; however, when encoding a video to a different framerate, in order to make sure that the overall video speed will stay the same, the process can cause some drawings to be *elongated*, and in turn some drawings to be *shortened*. **This means that there can be _more than one_ unique drawings in the time period of 1/24th of a second!** If you use the `>` button to step through the video, it will completely miss, for example, [this](https://i.imgur.com/Yhcl5Z8.png), [this](https://i.imgur.com/bGjTCDt.png) and [this](https://i.imgur.com/q6AJaXY.png) frame/drawing. (I captured these frames in an external video player.)

I hope I made the issue clear.

**Comment by ftLoic** [comment]
Corrected with 1.1.4
This is not the most convenient way (On a video, click on Settings under it -> Change framerate and set it to 30) but I believe this is a rare case, so it's better to make it 24 FPS by default
