### ISSUE TITLE
Make the sorting options more obvious

### ISSUE THREAD

**Issue by GitExploraa** [ftLoic/Sakuga-Extended#3]
in the main search page, sorting by date/id_desc means showing the most recently updated posts first, wether on the favorites page sorting by date shows the most recently favorited posts first while id_desc shows the most recently updated first and this is kinda confusing tbh

the better thing would be to give us one simple option (sort by uploaded date/ sort by favorited date) to clear up the confusion

hope my suggestion is useful

**Comment by ftLoic** [comment]
Hey, thanks for your submission!
Indeed, I didn't think about the favorited date, I'll try to add it soon

**Comment by GitExploraa** [comment]
great, I'll be looking forward to it and thank you
